name: Todo app CD - Azure SWA

on:
  push:
    branches:
      - main
    paths:
      - 'todoapp/**'
      - '.github/workflows/todoapp-azureswa-pipeline.yml'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy on Azure
    permissions:
       id-token: write
       contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js v22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' 
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Build And Deploy Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_ROCK_048C6970F }}
          action: "upload"
          app_location: "./todoapp"
          api_location: ""
          output_location: "dist/todoapp/browser"
          github_id_token: ${{ steps.idtoken.outputs.result }}
